FROM cypress/included:11.2.0

ARG GROUP_ID
ARG USER_ID
ENV USER_NAME="abc123def456ghi789"

RUN if ! id -gn "${GROUP_ID}" > /dev/null 2>&1; then echo "create new group: ${USER_NAME} with id *${GROUP_ID}*"; addgroup --gid "${GROUP_ID}" "${USER_NAME}"; fi
RUN if ! id -un "${USER_ID}" > /dev/null 2>&1; then echo "create new user: ${USER_NAME} with id *${USER_ID}* for group id *${GROUP_ID}*"; useradd "${USER_NAME}" -m -l -u "${USER_ID}" -g "${GROUP_ID}"; fi

RUN mkdir -p /root/.cache/
RUN chown -R "${USER_ID}":"${GROUP_ID}" /root/.cache/

RUN mkdir /apps && chown -R "${USER_ID}":"${GROUP_ID}" /apps
RUN mkdir /coverage-plugin && chown -R "${USER_ID}":"${GROUP_ID}" /coverage-plugin
USER "${USER_ID}":"${GROUP_ID}"
WORKDIR /coverage-plugin
RUN npm init -y && npm install -D @cypress/code-coverage
# Patch reporter
RUN sed -i 's/getSource(filePath) {/getSource(filePath){if(process.env.MAPP_REPORT_PATH){filePath=process.env.MAPP_REPORT_PATH+filePath}/'  /coverage-plugin/node_modules/istanbul-lib-report/lib/context.js