FROM node:20

ARG GROUP_ID
ARG USER_ID
ENV USER_NAME="abc123def456ghi789"
ENV NG_CLI_ANALYTICS="false"

RUN if ! id -gn "${GROUP_ID}" > /dev/null 2>&1; then echo "create new group: ${USER_NAME} with id *${GROUP_ID}*"; addgroup --gid "${GROUP_ID}" "${USER_NAME}"; fi
RUN if ! id -un "${USER_ID}" > /dev/null 2>&1; then echo "create new user: ${USER_NAME} with id *${USER_ID}* for group id *${GROUP_ID}*"; useradd "${USER_NAME}" -m -l -u "${USER_ID}" -g "${GROUP_ID}"; fi
WORKDIR /var/apps
RUN chown -R "${USER_ID}":"${GROUP_ID}" /var/apps
RUN npm install -g nyc
USER "${USER_ID}":"${GROUP_ID}"

RUN mkdir angular18 && cd angular18 && npm init -y && npm i @angular/cli@18
RUN mkdir angular17 && cd angular17 && npm init -y && npm i @angular/cli@17
RUN mkdir angular16 && cd angular16 && npm init -y && npm i @angular/cli@16
RUN mkdir angular15 && cd angular15 && npm init -y && npm i @angular/cli@15
RUN mkdir angular14 && cd angular14 && npm init -y && npm i @angular/cli@14
